### PR TITLE
ES6 babel transpile setup for npm package geojson-rbush

### PR DESCRIPTION
**Pull request by mholkesvik**
Hello Denis - 

Submitting a proposal for new setup with smoother ES6 compilation. Older browser can't handle the `const` in your source. I noticed you've provided an ES5 CDN link, but the current source is 404'ing and unpkg has been security compromised in the past and it seems best to move all ES6 out of the published NPM package. 

https://news.ycombinator.com/item?id=14111499

proposed setup and babel instructions available here: https://booker.codes/how-to-build-and-publish-es6-npm-modules-today-with-babel/

Let me know if there are any hesitations or questions, thanks for your open source work!

Mike

### CODE REVIEW

**Comment by DenisCarriere** [comment]
Actually the code is already in ES5, const is supported by IE 9.

If you really want, you can change those variables to `var`

**Comment by mholkesvik** [comment]
@DenisCarriere sounds good. Switching out the `const` also solves my problem (though from what I've seen IE9 does *not* support const).

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/const

> It is not supported in Internet Explorer 6-10, but is included in Internet Explorer 11

Thanks for the prompt reply!

**Comment by DenisCarriere** [comment]
👍 Learn something everyday... I really thought that `const` was supported, guess not! Thanks for the clarity on this.

**Comment by DenisCarriere** [comment]
@mholkesvik I just published a patch released `v1.1.1` with these changes.

**Pull request closed without merging**
