### PR TITLE
Update turf deps to v4.x

### PR DESCRIPTION
**Pull request by amenadiel**
Updates turf deps

- turf/bbox: from "^3.10.5" to  "^4.6.0"
- turf/helpers: from "^3.10.5" to  "^4.6.0"
- turf/meta: from "^3.10.5" to "^4.6.0"

### CODE REVIEW

**Comment by DenisCarriere** [comment]
Thanks good catch, might try to remove all dependencies after this merge.

**Comment by amenadiel** [comment]
@DenisCarriere could you please update the version in package.json and tag it. NPM is still returning the former version for me :cry:

**Comment by DenisCarriere** [comment]
That's because I didn't publish a new release yet.

**Comment by DenisCarriere** [comment]
Should be now published under `v1.2.0`, internalized a few TurfJS libraries, only kept `@turf/meta`

**Pull request merged**
